sudo: required
dist: cosmic
before_install:
- sudo apt-get --quiet update 
- sudo apt-get --quiet install python3 python3-pip
script:
- source ./bin/conf.sh 
- make venv && source ./build/venv/bin/activate
- ARCHS="native" KERNELS="block/aes hash/sha* mp/*" make clean build-libscarv build-test generate-test validate-test
