sudo: required
dist: cosmic
before_install:
- sudo apt-get --quiet update 
install:
- sudo apt-get --quiet install python3 python3-pip python3-venv
- python3 -m pip install -r ./requirements.txt
script:
- source ./bin/conf.sh 
- ARCHS="native" KERNELS="block/aes hash/sha* mp/*" make clean build-libscarv build-test generate-test validate-test
