sudo: required
dist: cosmic
before_install:
- sudo apt-get --quiet update 
install:
- sudo apt-get --quiet install docker.io
script:
- source ./bin/conf.sh 
- CONTEXT="docker" ARCH="native"        KERNELS="mp/* stream/*" make clean build-libscarv build-test generate-test validate-test
- CONTEXT="docker" ARCH="riscv"         KERNELS="mp/* stream/*" make clean build-libscarv build-test generate-test validate-test
- CONTEXT="docker" ARCH="riscv-xcrypto" KERNELS="mp/* stream/*" make clean build-libscarv build-test generate-test validate-test
