sudo: required
dist: cosmic
before_install:
- sudo apt-get --quiet update 
install:
- sudo apt-get --quiet install docker.io
script:
- source ./bin/conf.sh 
- HOST="docker" ARCHS="native riscv-xcrypto" KERNELS="mp/*" make clean build-libscarv build-test generate-test validate-test
