sudo: required
dist: cosmic
before_install:
- sudo apt-get -qq update 
- sudo apt-get -qq install python3 python3-pip python3-venv
script:
- source ./bin/conf.sh 
- make venv && source ./build/venv/bin/activate
- ARCHS="native" KERNELS="block/aes hash/sha* mp/*" make clean build-libscarv build-test generate-test validate-test
